// List of songs (you can add your own)
const songs = [
    "I Follow Rivers - Lykke Li",
    "Holocene - Bon Iver",
    "Lisztomania - Phoenix",
    "Mykonos - Fleet Foxes",
    "Saturn - Sleeping at Last",
    "Youth - Daughter",
    "The Suburbs - Arcade Fire",
    "The Fear - Ben Howard",
    "Home - Edward Sharpe & The Magnetic Zeros",
    "Oblivion - Grimes",
    "Young Blood - The Naked and Famous",
    "Silver Lining - First Aid Kit",
    "Elephant Gun - Beirut",
    "Bloodbuzz Ohio - The National",
    "Awake My Soul - Mumford & Sons",
    "Two Weeks - Grizzly Bear",
    "Re: Stacks - Bon Iver",
    "Wolf Like Me - TV on the Radio",
    "Do I Wanna Know? - Arctic Monkeys",
    "My Number - Foals",
    "Kettering - The Antlers",
    "Holland, 1945 - Neutral Milk Hotel",
    "Sweater Weather - The Neighbourhood",
    "Wide Eyes - Local Natives",
    "Australia - The Shins",
    "Pumped Up Kicks - Foster the People",
    "Toothpaste Kisses - The Maccabees",
    "Houdini - Foster the People",
    "Feel Real - Deptford Goth",
    "Lost in My Mind - The Head and the Heart",
    "Blood - The Middle East",
    "Harvest Moon - Poolside",
    "Shadows - Warpaint",
    "Dissolve Me - alt-J",
    "Eyes Wide Open - Gotye",
    "Gold - Chet Faker",
    "So Good at Being in Trouble - Unknown Mortal Orchestra",
    "No Diggity - Chet Faker",
    "Home - LCD Soundsystem",
    "1957 - Milo Greene",
    "Your Hand in Mine - Explosions in the Sky",
    "Flaws - Bastille",
    "The Wolves (Act I and II) - Bon Iver",
    "Caring Is Creepy - The Shins",
    "First - Cold War Kids",
    "Shelter Song - Temples",
    "Bloodflows - SOHN",
    "Come a Little Closer - Cage the Elephant",
    "Sleepyhead - Passion Pit",
    "Past Lives - BØRNS",
    "Swim and Sleep (Like a Shark) - Unknown Mortal Orchestra",
    "Red Eyes - The War on Drugs",
    "Carry Me - Bombay Bicycle Club",
    "Simple Song - The Shins",
    "Wicked Games - The Weeknd",
    "Ho Hey - The Lumineers",
    "Los Angeles, I'm Yours - The Decemberists",
    "Evil - Interpol",
    "Breezeblocks - alt-J",
    "Wires - The Neighbourhood",
    "Take Me to Church - Hozier",
    "Horchata - Vampire Weekend",
    "Bravado - Lorde",
    "Demons - Sleigh Bells",
    "Anna Sun - Walk the Moon",
    "Agoraphobia - Deerhunter",
    "Fever - The Black Keys",
    "Heartbeats - José González",
    "Flume - Bon Iver",
    "Disparate Youth - Santigold",
    "The Walker - Fitz and The Tantrums",
    "Every Other Freckle - alt-J",
    "Holocene - Bon Iver",
    "Dirty Paws - Of Monsters and Men",
    "Gun - CHVRCHES",
    "Electric Feel - MGMT",
    "Something Good Can Work - Two Door Cinema Club",
    "Crystalised - The xx",
    "Midnight City - M83",
    "Welcome Home - Radical Face",
    "Down by the Water - The Decemberists",
    "Amsterdam - Imagine Dragons",
    "Reflektor - Arcade Fire",
    "All I Want - Kodaline",
    "Love is to Die - Warpaint",
    "Scarborough Fair/Canticle - Simon & Garfunkel",
    "Gold on the Ceiling - The Black Keys",
    "O Children - Nick Cave & The Bad Seeds",
    "Redbone - Childish Gambino",
    "Shake It Out - Florence + The Machine",
    "Broken Bones - CHVRCHES",
    "Sunset - The xx",
    "1904 - The Tallest Man on Earth",
    "Gooey - Glass Animals",
    "All Your Light (Times Like These) - Portugal. The Man",
    "Your Rocky Spine - Great Lake Swimmers",
    "From the Morning - Nick Drake",
    "Harvest Moon - Neil Young",
    "Heavenly Father - Bon Iver",
    "Eugene - Arlo Parks",
"Chronos - Hania Rani",
"Temple - Thao & The Get Down Stay Down",
"Reverie - Tennyson",
"Bambro Koyo Ganda - Bonobo",
"Munich - Editors",
"Diamond Heart - Alan Walker ft. Sophia Somajo",
"Cleopatra - The Lumineers",
"Do Si Do - Jenny Lewis",
"Amber - 311",
"Barracuda - Heart",
"Sleep on the Floor - The Lumineers",
"Sober Up - AJR ft. Rivers Cuomo",
"Colors - Black Pumas",
"Primavera - Ludovico Einaudi",
"Shark Smile - Big Thief",
"San Francisco - Foxygen",
"She's Kerosene - The Interrupters",
"Kill V. Maim - Grimes",
"Only God Knows - Young Fathers",
"Salt - B.Miles",
"Holy Roller - Emily Wolfe",
"Cut Me - Moses Sumney",
"Souvenir - Boy Harsher",
"The Steps - HAIM",
"I'm Ready - Sam Smith ft. Demi Lovato",
"This Land - Gary Clark Jr.",
"Waves - Miguel",
"Second One to Know - Chris Stapleton",
"Dancing On My Own - Robyn",
"The Highwomen - The Highwomen",
"Fever - Roosevelt",
"Midnight City - M83",
"Brace for Impact (Live a Little) - Sturgill Simpson",
"Don't Start Now - Dua Lipa",
"Drugs - Ratatat",
"Oblivion - Grimes",
"Sprinter - Torres",
"Beyond - Leon Bridges",
"Never Going Back Again - Fleetwood Mac",
"The Less I Know The Better - Tame Impala",
"Let It Happen - Tame Impala",
"1940 (AmpLive Remix) - The Submarines",
"Nobody Speak - DJ Shadow ft. Run The Jewels",
"Electric Feel - MGMT",
"Me and Michael - MGMT",
"Juno - Tokyo Police Club",
"Clearest Blue - CHVRCHES",
"The Mother We Share - CHVRCHES",
"Shake Me Down - Cage The Elephant",
"Trouble - Cage The Elephant",
"Everlong - Foo Fighters",
"Walk - Foo Fighters",
"Wide Eyes - Local Natives",
"When Am I Gonna Lose You - Local Natives",
"Dust Bowl Dance - Mumford & Sons",
"Believe - Mumford & Sons",
"The Chain - Fleetwood Mac",
"Landslide - Fleetwood Mac",
"Dreams - Fleetwood Mac",
"Go Your Own Way - Fleetwood Mac",
"Electric Love - BØRNS",
"Past Lives - BØRNS",
"1901 - Phoenix",
"Lisztomania - Phoenix",
"You Only Live Once - The Strokes",
"Last Nite - The Strokes",
"Take Me Out - Franz Ferdinand",
"Do You Want To - Franz Ferdinand",
"Hey Ya! - OutKast",
"Ms. Jackson - OutKast",
"Smile Like You Mean It - The Killers",
"Somebody Told Me - The Killers",
"Naive - The Kooks",
"She Moves in Her Own Way - The Kooks",
"Fluorescent Adolescent - Arctic Monkeys",
"Do I Wanna Know? - Arctic Monkeys",
"Young Folks - Peter Bjorn and John",
"Up Against the Wall - Peter Bjorn and John",
"Pumped Up Kicks - Foster The People",
"Helena Beat - Foster The People",
"Kids - MGMT",
"Time to Pretend - MGMT",
"1901 - Phoenix",
"Listzomania - Phoenix",
"Float On - Modest Mouse",
"Dashboard - Modest Mouse",
"Feel Good Inc. - Gorillaz",
"Clint Eastwood - Gorillaz",
"Dani California - Red Hot Chili Peppers",
"Californication - Red Hot Chili Peppers",
"Somebody Told Me - The Killers",
"Mr. Brightside - The Killers",
"Under The Bridge - Red Hot Chili Peppers",
"By The Way - Red Hot Chili Peppers",
"Use Somebody - Kings of Leon",
"Sex on Fire - Kings of Leon",
"Island in the Sun - Weezer",
"Buddy Holly - Weezer",
"Scar Tissue - Red Hot Chili Peppers",
"Harmony Hall - Vampire Weekend",
"Lost In Yesterday - Tame Impala",
"Your Power - Billie Eilish",
"Space Song - Beach House",
"The Less I Know the Better - Tame Impala",
"Let It Happen - Tame Impala",
"Circles - Post Malone",
"The Adults Are Talking - The Strokes",
"Nangs - Tame Impala",
"Waves - Kanye West",
"Such Great Heights - The Postal Service",
"Say It Ain't So - Weezer",
"Latch - Disclosure ft. Sam Smith",
"Take Me to Church - Hozier",
"Bad Guy - Billie Eilish",
"1901 - Phoenix",
"Ribs - Lorde",
"Feels Like We Only Go Backwards - Tame Impala",
"Budapest - George Ezra",
"Take Care - Beach House",
"Yellow - Coldplay",
"Midnight City - M83",
"Sober - Childish Gambino",
"Pumped Up Kicks - Foster The People",
"Do I Wanna Know? - Arctic Monkeys",
"Love It If We Made It - The 1975",
"Skinny Love - Bon Iver",
"Somebody Else - The 1975",
"Feel Good Inc. - Gorillaz",
"Kids - MGMT",
"Electric Feel - MGMT",
"Africa - Toto",
"Breezeblocks - alt-J",
"Get Lucky - Daft Punk ft. Pharrell Williams",
"The Less I Know The Better - Tame Impala",
"Lisztomania - Phoenix",
"Pumped Up Kicks - Foster The People",
"Dog Days Are Over - Florence + The Machine",
"Electric Love - BØRNS",
"Mr. Brightside - The Killers",
"Somebody Told Me - The Killers",
"Stubborn Love - The Lumineers",
"Ophelia - The Lumineers",
"Riptide - Vance Joy",
"Hey Ho - The Lumineers",
"A-Punk - Vampire Weekend",
"Harlem - New Politics",
"Take Me Out - Franz Ferdinand",
"A-Punk - Vampire Weekend",
"Helena Beat - Foster The People",
"Shake Me Down - Cage The Elephant",
"Sleepyhead - Passion Pit",
"1901 - Phoenix",
"Island In The Sun - Weezer",
"Tongue Tied - Grouplove",
"I Bet You Look Good On The Dancefloor - Arctic Monkeys",
"Somewhere Only We Know - Keane",
"Animal - Neon Trees",
"Cigarette Daydreams - Cage The Elephant",
"Sweater Weather - The Neighbourhood",
"Do You - Spoon",
"Run - Vampire Weekend",
"Love Love Love - Of Monsters and Men",
"Walcott - Vampire Weekend",
"Pumped Up Kicks - Foster The People",
"Two Weeks - Grizzly Bear",
"Float On - Modest Mouse",
"Hey Ya! - OutKast",
"First - Cold War Kids",
"1904 - The Tallest Man On Earth",
"I Will Follow You Into The Dark - Death Cab for Cutie",
"Houdini - Foster The People",
"When You Were Young - The Killers",
"Somebody Told Me - The Killers",
"Ride - Twenty One Pilots",
"Cherry Wine - Hozier",
"Black Sun - Death Cab for Cutie",
"Dreaming - Smallpools",
"Naive - The Kooks",
"What You Know - Two Door Cinema Club",
"Electric Feel - MGMT",
"Take a Walk - Passion Pit",
"Tongue Tied - Grouplove",
"Down by the Water - The Drums",
"Cardiac Arrest - Bad Suns",
"Youth - Glass Animals",
"Getaway - Saint Motel",
"Dissolve Me - alt-J",
"The Sound - The 1975",
"Little Talks - Of Monsters and Men",
"Waves - Sleeper Agent",
"Peach (Lobotomy) - The Front Bottoms",
"All the Small Things - blink-182",
"Sweet Disposition - The Temper Trap",
"What You Know - Two Door Cinema Club",
"Are You What You Want To Be? - Foster The People",
"Don't You (Forget About Me) - Simple Minds",
"Mr. Jones - Counting Crows",
"Slide - Calvin Harris ft. Frank Ocean & Migos",
"Electric Feel - MGMT"
    
    
  ];
  
  function generateRandomSong() {
    const randomIndex = Math.floor(Math.random() * songs.length);
    return songs[randomIndex];
  }
  
  document.getElementById('generateButton').addEventListener('click', function() {
    const songDisplay = document.getElementById('songDisplay');
    const randomSong = generateRandomSong();
  
    const spotifyLink = `https://open.spotify.com/search/${encodeURIComponent(randomSong)}`;
  
    const songLink = document.createElement('a');
    songLink.href = spotifyLink;
    songLink.target = '_blank';
  
    const songTitle = document.createElement('span');
    songTitle.textContent = randomSong;
  
    const spotifyText = document.createElement('span');
    spotifyText.textContent = ' Spotify';
  
    songLink.appendChild(songTitle);
    songLink.appendChild(document.createTextNode(' ')); // Add space between title and Spotify text
    songLink.appendChild(spotifyText);
  
    songDisplay.innerHTML = '';
    songDisplay.appendChild(songLink);
  });

  